kafka_producer:
  brokers:
    - "kafka:9092"
  topic: "logs"
  acks: -1
  retries: 3
  batch_size: 16384
  linger_ms: 1
  compression_type: "gzip"
  sources:
    - name: "serviceA"
      environment: "production"
      severity_level: "INFO"
    - name: "serviceB"
      environment: "staging"
      severity_level: "WARN"
    - name: "serviceC"
      environment: "development"
      severity_level: "DEBUG"
    - name: "serviceD"
      environment: "production"
      severity_level: "ERROR"
