kafka_consumer:
  brokers:
    - "kafka:9092"
  group_id: "log-consumers"
  topic: "logs"
  auto_offset_reset: "earliest"
  max_wait_time: 100
  min_bytes: 1
  max_bytes: 1048576

  filtering:
    min_severity: "INFO"  # Minimum severity level for logs to be processed (DEBUG, INFO, WARN, ERROR)
    
  enrichment:
    add_timestamp: true  # Add a timestamp to each log
    add_host_info: true  # Add host information

  retry:
    max_retries: 5            # Maximum number of retries for transient errors
    initial_backoff_ms: 100   # Initial backoff time in milliseconds
    max_backoff_ms: 2000      # Maximum backoff time in milliseconds
